export const filtros = {
  hair_color: [
    "auburn",
    "auburn, grey",
    "auburn, white",
    "black",
    "blond",
    "blonde",
    "brown",
    "brown, grey",
    "grey",
    "n/a",
    "none",
    "white"
  ],
  skin_color: [
    "blue",
    "blue, grey",
    "brown",
    "brown mottle",
    "brown, white",
    "dark",
    "fair",
    "fair, green, yellow",
    "gold",
    "green",
    "green, grey",
    "green-tan, brown",
    "grey",
    "grey, blue",
    "grey, green, yellow",
    "grey, red",
    "light",
    "metal",
    "mottled green",
    "orange",
    "pale",
    "red",
    "red, blue, white",
    "silver, red",
    "tan",
    "unknown",
    "white",
    "white, blue",
    "white, red",
    "yellow"
  ],
  eye_color: [
    "black",
    "blue",
    "blue-gray",
    "brown",
    "gold",
    "green, yellow",
    "hazel",
    "orange",
    "pink",
    "red",
    "red, blue",
    "unknown",
    "white",
    "yellow"
  ],
  gender: [
    "female",
    "hermaphrodite",
    "male",
    "n/a",
    "none"
  ]
};

