import { Inter } from "next/font/google";
import {  } from "../public/chewbacca_icon.svg";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "StarWars",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <head>
        <link rel="shortcut icon" href="/chewbacca_icon.svg" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
