import "./globals.css";
import { trispace } from "./fonts.js";
import Header from "./components/header/Header.jsx";
import Footer from "./components/footer/Footer.jsx";

export const metadata = {
  title: "StarWars",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <head>
        <link rel="shortcut icon" href="/chewbacca_icon.svg" />
      </head>

      <body className={`${trispace.className} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
